Repository ita-social-projects/GreenCityUBS, pull requests merged in 2021-06, with the labels that each got.

#139 2842_ubs_client done
  core/src/main/java/greencity/configuration/SecurityConfig.java
  core/src/main/java/greencity/controller/ClientController.java
  core/src/main/java/greencity/exception/handler/CustomExceptionHandler.java
  core/src/test/java/greencity/ModelUtils.java
  core/src/test/java/greencity/controller/ClientControllerTest.java
  dao/src/main/java/greencity/repository/OrderRepository.java
  service-api/src/main/java/greencity/constant/ErrorMessage.java
  service-api/src/main/java/greencity/dto/OrderBagDto.java
  service-api/src/main/java/greencity/dto/OrderClientDto.java
  service-api/src/main/java/greencity/exceptions/BadOrderStatusRequestException.java
  service-api/src/main/java/greencity/exceptions/OrderNotFoundException.java
  service-api/src/main/java/greencity/service/ubs/UBSClientService.java
  service/src/main/java/greencity/mapping/OrderBagDtoMapper.java
  service/src/main/java/greencity/mapping/OrderClientDtoMapper.java
  service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
  service/src/test/java/greencity/ModelUtils.java
  service/src/test/java/greencity/mapping/OrderClientDtoMapperTest.java
  service/src/test/java/greencity/service/UBSClientServiceImplTest.java
Labels: enhancement

#143 Created controller which save or update user`s date UserProfileContro…
  core/src/main/java/greencity/controller/UserProfileController.java
  core/src/test/java/greencity/ModelUtils.java
  core/src/test/java/greencity/controller/UserProfileControllerTest.java
  dao/src/main/java/greencity/entity/user/User.java
  dao/src/main/resources/db/changelog/db.changelog-master.xml
  dao/src/main/resources/db/changelog/logs/ch-add-column-users-surname-Berezhinkiy.xml
  service-api/src/main/java/greencity/dto/AddressDto.java
  service-api/src/main/java/greencity/dto/UserProfileDto.java
  service-api/src/main/java/greencity/service/ubs/UBSClientService.java
  service/src/main/java/greencity/constant/AppConstant.java
  service/src/main/java/greencity/mapping/AddressDtoMapper.java
  service/src/main/java/greencity/mapping/UserToUserProfileDtoMapper.java
  service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
  service/src/test/java/greencity/ModelUtils.java
  service/src/test/java/greencity/service/UBSClientServiceImplTest.java
Labels: enhancement

#145 Created two controllers, first controller returns info about user, ubs…
  core/src/main/java/greencity/controller/OrderController.java
  core/src/test/java/greencity/ModelUtils.java
  core/src/test/java/greencity/controller/OrderControllerTest.java
  dao/src/main/java/greencity/repository/UserRepository.java
  service-api/src/main/java/greencity/constant/ErrorMessage.java
  service-api/src/main/java/greencity/dto/UbsCustomersDto.java
  service-api/src/main/java/greencity/dto/UbsCustomersDtoUpdate.java
  service-api/src/main/java/greencity/dto/UserInfoDto.java
  service-api/src/main/java/greencity/exceptions/UBSuserNotFoundException.java
  service-api/src/main/java/greencity/service/ubs/UBSClientService.java
  service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
  service/src/test/java/greencity/ModelUtils.java
  service/src/test/java/greencity/service/UBSClientServiceImplTest.java
Labels: do not merge, enhancement, work in progress

#151 Fix bug
  service/src/main/java/greencity/constant/AppConstant.java
  service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
  service/src/main/java/greencity/service/ubs/UBSEmployeeServiceImpl.java
Labels: bug

#153 fix server error
  core/src/main/resources/application-dev.properties
  service/src/main/java/greencity/constant/AppConstant.java
  service/src/main/java/greencity/service/ubs/UBSManagementEmployeeServiceImpl.java
Labels: bug

#158 Certificate status become "USED" only after payment confirmation now.
  service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
Labels: bug

#154 Return information about user rule violations for the current order m…
  core/src/test/java/greencity/ModelUtils.java
  dao/src/main/java/greencity/repository/UserRepository.java
  service-api/src/main/java/greencity/dto/UserInfoDto.java
  service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
  service/src/test/java/greencity/ModelUtils.java
  service/src/test/java/greencity/service/UBSClientServiceImplTest.java
Labels: review

#161 Fix bug in OrderClientDto
  service/src/main/java/greencity/mapping/OrderClientDtoMapper.java
  service/src/test/java/greencity/mapping/OrderClientDtoMapperTest.java
Labels: bug

#164 Duplicate values #2923
  dao/src/main/java/greencity/repository/AllValuesFromTableRepo.java
  service-api/src/main/java/greencity/dto/AllFieldsFromTableDto.java
Labels: bug
