Repository ita-social-projects/GreenCityUBS, pull requests merged in 2025-08, with the labels that each got.

#1760 feature/1757/create-documentation-for-telegram-chat-sockets
  core/src/main/java/greencity/configuration/SecurityConfig.java
  core/src/main/resources/application.properties
  service-api/src/main/java/greencity/service/ubs/TelegramNotificationService.java
  service/pom.xml
  service/src/main/java/greencity/producers/TelegramChatProducer.java
  service/src/main/java/greencity/ubstelegrambot/service/TelegramNotificationServiceImpl.java
  service/src/main/java/greencity/ubstelegrambot/service/TelegramServiceImpl.java
  service/src/main/java/greencity/ubstelegrambot/service/TelegramSupportServiceImpl.java
  service/src/test/java/greencity/producers/TelegramChatProducerTest.java
  service/src/test/java/greencity/ubstelegrambot/TelegramNotificationServiceTest.java
  service/src/test/java/greencity/ubstelegrambot/TelegramServiceTest.java
  service/src/test/java/greencity/ubstelegrambot/TelegramSupportServiceTest.java
Labels: documentation, enhancement, dependencies

#1768 Feature: replace localDateTime with utc Instant in telegram entities
  dao/src/main/java/greencity/entity/telegram/MessageAsset.java
  dao/src/main/java/greencity/entity/telegram/TelegramChat.java
  dao/src/main/java/greencity/entity/telegram/TelegramMessage.java
  dao/src/main/resources/db/changelog/db.changelog-master.xml
  dao/src/main/resources/db/changelog/logs/2025-08-07-ch-update-localdatetime-to-instant-in-telegram-entities.xml
  dao/src/main/resources/db/changelog/logs/2025-08-08-ch-update-chat-state-updated-at-field-in-telegram-chat.xml
  service-api/src/main/java/greencity/dto/telegram/TelegramMessageDto.java
  service/src/main/java/greencity/ubstelegrambot/service/TelegramFeedbackServiceImpl.java
  service/src/main/java/greencity/ubstelegrambot/service/TelegramGreenOfficeServiceImpl.java
  service/src/main/java/greencity/ubstelegrambot/service/TelegramServiceImpl.java
  service/src/main/java/greencity/ubstelegrambot/service/TelegramSupportServiceImpl.java
  service/src/main/java/greencity/ubstelegrambot/service/TelegramUtils.java
  service/src/test/java/greencity/ModelUtils.java
  service/src/test/java/greencity/ubstelegrambot/TelegramServiceTest.java
  service/src/test/java/greencity/ubstelegrambot/service/TelegramFeedbackServiceTest.java
  service/src/test/java/greencity/ubstelegrambot/service/TelegramNotificationServiceTest.java
Labels: bug, enhancement, chat, java

#1762 Bugfix: sorting chats with last message null
  .github/workflows/main.yml
  core/src/main/java/greencity/controller/TelegramController.java
  dao/src/main/java/greencity/entity/telegram/TelegramChat.java
  dao/src/main/java/greencity/repository/TelegramChatRepository.java
  dao/src/main/java/greencity/specification/ChatSpecifications.java
  dao/src/main/resources/db/changelog/db.changelog-master.xml
  dao/src/main/resources/db/changelog/logs/2025-08-07-ch-add-created-at-to-telegram-chat.xml
  service/src/main/java/greencity/ubstelegrambot/service/TelegramServiceImpl.java
  service/src/test/java/greencity/ModelUtils.java
  service/src/test/java/greencity/ubstelegrambot/service/TelegramNotificationServiceTest.java
Labels: bug, java

#1775 Feature #1774 added additional springwolf configurations
  core/src/main/resources/application.properties
Labels: documentation, enhancement

#1771 Bugfix - Refactor Manual Dependency Injection for Telegram Bot
  core/src/main/java/greencity/exception/handler/CustomExceptionHandler.java
  core/src/test/java/greencity/repository/BigOrderTableRepositoryTest.java
  service-api/src/main/java/greencity/constant/ErrorMessage.java
  service-api/src/main/java/greencity/exceptions/bots/MessageWasNotSent.java
  service-api/src/main/java/greencity/exceptions/bots/TelegramBotExecutionException.java
  service-api/src/main/java/greencity/service/ubs/TelegramService.java
  service/src/main/java/greencity/config/TelegramBotConfig.java
  service/src/main/java/greencity/ubstelegrambot/UBSTelegramBot.java
  service/src/main/java/greencity/ubstelegrambot/service/TelegramExecutor.java
  service/src/main/java/greencity/ubstelegrambot/service/TelegramNotificationService.java
  service/src/main/java/greencity/ubstelegrambot/service/TelegramNotificationServiceImpl.java
  service/src/main/java/greencity/ubstelegrambot/service/TelegramServiceImpl.java
  service/src/main/java/greencity/ubstelegrambot/service/TelegramSupportServiceImpl.java
  service/src/test/java/greencity/ubstelegrambot/TelegramNotificationServiceTest.java
  service/src/test/java/greencity/ubstelegrambot/TelegramServiceTest.java
  service/src/test/java/greencity/ubstelegrambot/TelegramSupportServiceTest.java
  service/src/test/java/greencity/ubstelegrambot/UBSTelegramBotTest.java
  service/src/test/java/greencity/ubstelegrambot/service/TelegramExecutorTest.java
  service/src/test/java/greencity/ubstelegrambot/service/TelegramNotificationServiceTest.java
Labels: enhancement
